//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

ifndef::env-github[]
ifeval::["{backend}" == "manpage"]
:x_manpage:
endif::[]
endif::[]

ifdef::x_manpage[]

= qllm(1)
:doctype: manpage
:manmanual: qllm
:mansource: qllm

:x_long_option_1a: pass:n[**--foo=**<__bar__>]
:x_long_option_1b: pass:n[**--foo**{nbsp}<__bar__>]
:x_opt_d_name: pass:n[**-d**]
:x_opt_debug_name: pass:n[**--debug**]
:x_opt_m_arg: pass:n[<__model__>]
:x_opt_m_name: pass:n[**-m**]
:x_opt_m_name_arg: pass:n[**-m**{nbsp}<__model__>]
:x_opt_model_arg: pass:n[<__model__>]
:x_opt_model_name: pass:n[**--model**]
:x_opt_model_name_arg: pass:n[**--model=**<__model__>]
:x_opt_terminator: pass:n[**--**]
:x_qllm: pass:n[**qllm**]
:x_qllm_option: pass:n[<__option__>]
:x_qllm_session_file: pass:n[<__session_file__>]
:x_short_option_1a: pass:n[**-f**{nbsp}<__bar__>]
:x_short_option_1b: pass:n[**-f**<__bar__>]
:x_short_option_2a: pass:n[**-f**]
:x_short_option_2b: pass:n[**-g**]
:x_short_option_2c: pass:n[**-fg**]
:x_short_option_2d: pass:n[**-f{nbsp}-g**]
:x_var_EDITOR: pass:n[**EDITOR**]
:x_var_EDITOR_BOTTOM: pass:n[**EDITOR_BOTTOM**]
:x_var_VISUAL: pass:n[**VISUAL**]
:x_var_VISUAL_BOTTOM: pass:n[**VISUAL_BOTTOM**]
:x_var_VISUAL_eq_vi: pass:n[**VISUAL=vi**]
:x_var_default_editor_bottom: pass:n[**-c '$'**]
:x_vi: pass:n[**vi**]
:x_vim: pass:n[**vim**]

endif::[]

ifndef::x_manpage[]

= `qllm`

:x_long_option_1a: pass:n[``--foo=<bar>``]
:x_long_option_1b: pass:n[``--foo{nbsp}<bar>``]
:x_opt_d_name: pass:n[``-d``]
:x_opt_debug_name: pass:n[``--debug``]
:x_opt_m_arg: pass:n[``<model>``]
:x_opt_m_name: pass:n[``-m``]
:x_opt_m_name_arg: pass:n[``-m{nbsp}<model>``]
:x_opt_model_arg: pass:n[``<model>``]
:x_opt_model_name: pass:n[``--model``]
:x_opt_model_name_arg: pass:n[``--model=<model>``]
:x_opt_terminator: pass:n[``--``]
:x_qllm: pass:n[``qllm``]
:x_qllm_option: pass:n[``<option>``]
:x_qllm_session_file: pass:n[``<session_file>``]
:x_short_option_1a: pass:n[``-f{nbsp}<bar>``]
:x_short_option_1b: pass:n[``-f<bar>``]
:x_short_option_2a: pass:n[``-f``]
:x_short_option_2b: pass:n[``-g``]
:x_short_option_2c: pass:n[``-fg``]
:x_short_option_2d: pass:n[``-f{nbsp}-g``]
:x_var_EDITOR: pass:n[``EDITOR``]
:x_var_EDITOR_BOTTOM: pass:n[``EDITOR_BOTTOM``]
:x_var_VISUAL: pass:n[``VISUAL``]
:x_var_VISUAL_BOTTOM: pass:n[``VISUAL_BOTTOM``]
:x_var_VISUAL_eq_vi: pass:n[``VISUAL=vi``]
:x_var_default_editor_bottom: pass:n[``-c '$'``]
:x_vi: pass:n[``vi``]
:x_vim: pass:n[``vim``]

endif::[]

:x_qllm_tagline: Large language model CLI wrapper

:x_subs_normal: attributes,specialchars,quotes,replacements,macros,post_replacements
:x_subs_source: attributes,specialchars,quotes,macros

== Name

ifdef::x_manpage[]
qllm - {x_qllm_tagline}
endif::[]

ifndef::x_manpage[]
{x_qllm} &#x2014; {x_qllm_tagline}
endif::[]

== Synopsis

ifdef::x_manpage[]
{x_qllm} ++[++{x_qllm_option}++...]++ ++[++{x_qllm_session_file}++]++
endif::[]

ifndef::x_manpage[]
----
qllm [<option>...] [<session_file>]
----
endif::[]

== Description

TODO

== Options

A long option with a required argument {x_long_option_1a} may also be
written as {x_long_option_1b}.
A short option with a required argument {x_short_option_1a} may also be
written as {x_short_option_1b} if the argument is not empty.
A short option with a forbidden argument {x_short_option_2a} may be
bundled with a subsequent short option or short option bundle
{x_short_option_2b} by writing {x_short_option_2c} instead of
{x_short_option_2d}.

{x_opt_terminator}:: All further arguments will be taken as operands
instead of possibly being taken as {x_qllm_option}s.

{x_opt_debug_name}, {x_opt_d_name}:: Print debug information to stderr.

{x_opt_model_name_arg}, {x_opt_m_name_arg}:: Use {x_opt_model_arg}
instead of the default model.

== Text file inputs

Text files can be added using the `@@@<` directive:

----
Explain this program and show me how to compile it.

@@@< main.c
----

== Inline text file inputs

Text files can be added inline using the `@@@<<` directive:

----
Explain this program and show me how to compile and run it.

@@@<< main.c
#include <stdio.h>
int main(void) {
  puts("Hello, qllm!");
  return 0;
}
@@@<<
----

When defining multiple inline text file inputs in a row, the
intermediate ending directives can be omitted:

----
Explain this program and show me how to compile and run it.

@@@<< hello_qllm.h
void hello_qllm(void);
@@@<< hello_qllm.c
#include <stdio.h>
void hello_qllm(void) {
  puts("Hello, qllm!");
}
@@@<< main.c
#include "hello_qllm.h"
int main(void) {
  hello_qllm();
  return 0;
}
@@@<<
----

== Environment variables

{x_var_VISUAL} or {x_var_EDITOR}::
The command to run your text editor.
The first of these variables that is set will be used.
If none of these variables are set, {x_vi} will be used by default.

{x_var_VISUAL_BOTTOM} or {x_var_EDITOR_BOTTOM}::
The arguments to pass to your text editor to make it scroll to the
bottom when opening a file.
Only the variable that matches the text editor variable you're using
will be used.
For example, {x_var_VISUAL_BOTTOM} will only be used if you're using
{x_var_VISUAL}.
If this variable is unset, it will be inferred if your text editor is
exactly either {x_vi} or {x_vim}.
For example, if you're using {x_var_VISUAL_eq_vi} and you leave
{x_var_VISUAL_BOTTOM} unset, it will be inferred as
{x_var_default_editor_bottom}.
If you're letting your text editor default to {x_vi}, this will default
to {x_var_default_editor_bottom}.

== Examples

TODO

//
